# possibly move to Hydra (FB) if things get complex.
dataset:
  data_dir: ../data/farsight
  depth_foldername: depth
  img_foldername: img
model:
  use_cuda: True
  use_saved: False
  path:
  weight_init: True
  randomize_seed: False
  name: UNet
  use_bn: True
  use_dropout: True
  loss: rmsle
  # randomdata?
  # shuffledata?
  lr: 1.e-2
  use_lr_scheduler: False
train:
  batch_size: 4
  epochs: 1000
  subset_size: 4
  use_folds: False
  val_round: False
  shuffle_val: True
  val_percent: 0.2
  run_name: 'aug-and-dropout'
  print_every: 100
  save: True
  save_every: 50
  data_augmentation:
    horizontal_flip: True
    flip_p: 0.5
    color_jitter: True
    gaussian_blur: True
    gaussian_noise: True
    # possibly add std and probability for augs over here?

evaluate: # TODO: actually take eval into account.
  batch_size: 10
  hist: False
verbose: True