# possibly move to Hydra (FB) if things get complex.
dataset:
  data_dir: ../data/farsight
  depth_foldername: depth
  img_foldername: img
model:
  use_cuda: True
  use_saved: False
  path:  12_23_15-00-03_full_100ep/
  weight_init: True
  name: UNet
  use_bn: True
  loss: rmsle
  # randomdata?
  # shuffledata?
  lr: 1.e-2
train:
  batch_size: 4
  epochs: 10
  subset_size: 20
  val_round: True
  val_percent: 0.2
  run_name: 'test'
  print_every: 1
  save: False
  save_every: 10
  # data_augmentation: # TODO: data augement.
  #   horizontal_flip: True
evaluate: # TODO: actually take eval into account.
  batch_size: 10
  hist: False
verbose: True