# possibly move to Hydra (FB) if things get complex.


dataset:
  data_dir: ../data/farsight
  depth_foldername: depth_without_bad_images
  img_foldername: img_without_bad_images
  test_foldername: test
  geopose_path: 'D:\Users\Ariel\Documents\DS הכשרה_\15. MDE with laser reference point\laser-mde\data\geoPose3K_img_and_depth'

misc:
  verbose: True
  random_seed: 42 # if none won't have constant seed.
  use_cuda: True
  use_trains: True

checkpoint:
  # if you load a checkpoint, run_name is ignored.
  # if save_every is empty, it won't save.
  use_saved: True # will continue in trains showing old config file.
  saved_path:
  run_name:
  save_every: 10

model:
  # is irrelevant if you're loading a saved model.
  # arch is prebuilt into the .pt file. easier to handle it.
  weight_init: True
  name: UNet
  use_bn: True
  use_double_bn: True
  dropout: 0.2

optim:
  loss: rmsle
  lr: 1.e-2
  use_lr_scheduler: False
  # randomdata?
  # shuffledata?

train:
  batch_size: 4
  epochs: 400
  subset_size:
  use_folds: True
  print_every: 1

validation:
  batch_size: 10
  val_round: True
  val_percent: 0.2
  shuffle_val: True
  hist: False

data_augmentation:
  flip_p: 0.5
  horizontal_flip: False
  color_jitter: False
  gaussian_blur: False
  gaussian_noise: False
  # possibly add std and probability for augs over here?
