# possibly move to Hydra (FB) if things get complex.
dataset:
  data_dir: ../data/farsight
  depth_foldername: depth
  img_foldername: img
model:
  use_cuda: True
  use_saved: False
  path:
  weight_init: True
  randomize_seed: False
  name: UNet
  use_bn: True
  use_double_bn: False
  use_dropout: False
  loss: rmsle
  # randomdata?
  # shuffledata?
  lr: 1.e-2
  use_lr_scheduler: False
train:
  batch_size: 4
  epochs: 1000
  subset_size: 20
  use_folds: True
  val_round: True
  shuffle_val: True
  val_percent: 0.2
  run_name: 'single_bn_toy_folds'
  print_every: 100
  save: False
  save_every:
  data_augmentation:
    horizontal_flip: False
    flip_p: 0.5
    color_jitter: False
    gaussian_blur: False
    gaussian_noise: False
    # possibly add std and probability for augs over here?

evaluate: # TODO: actually take eval into account.
  batch_size: 10
  hist: False
verbose: True