# possibly move to Hydra (FB) if things get complex.
dataset:
  data_dir: ../data/farsight
  depth_foldername: depth
  img_foldername: img
model:
  use_cuda: True
  script_path: ../models/optimized.py
  weight_init: True
  arch:
    name: UNet
    use_bn: True
  loss: #todo
optimizer:
  lr: 1.e-1
train:
  batch_size: 4
  epochs: 5
  subset_ds_size: 50
  val_round: True
  val_percent: 0.2
  run_name: ''
  print_every: 10
  data_augmentation:
    horizontal_flip: True
evaluate:
  batch_size: 1000
  augmentation_factor: 32
  data_augmentation:
