# possibly move to Hydra (FB) if things get complex.
dataset:
  data_dir: ../data/farsight
  depth_foldername: depth
  img_foldername: img

misc:
  verbose: True
  random_seed: 42 # if none won't have constant seed.
  use_cuda: True

checkpoint: # if you load a checkpoint, run_name is ignored.
  use_saved: False
  saved_path: 12_30_17-09-42_sanity-fold-full-dataset-w-aug
  run_name: test
  save_every:  # if empty won't save.

model:
  weight_init: True
  name: UNet
  use_bn: True
  use_double_bn: False
  use_dropout: False
  loss: rmsle
  lr: 1.e-2
  use_lr_scheduler: False
  # randomdata?
  # shuffledata?

train:
  batch_size: 4
  epochs: 1000
  subset_size:
  use_folds: True
  print_every: 100

validation:
  batch_size: 10
  val_round: True
  val_percent: 0.2
  shuffle_val: True
  hist: False

data_augmentation:
  flip_p: 0.5
  horizontal_flip: True
  color_jitter: True
  gaussian_blur: True
  gaussian_noise: True
  # possibly add std and probability for augs over here?
