# possibly move to Hydra (FB) if things get complex.
dataset:
  data_dir: ../data/farsight
  depth_foldername: depth
  img_foldername: img
model:
  use_cuda: True
  weight_init: True
  arch:
    name: UNet
    use_bn: True
  # loss: # TODO: use loss in get_net.
  # randomdata?
  # shuffledata?
  lr: 1.e-2
train:
  batch_size: 2
  epochs: 100
  subset_size: 2
  val_round: False
  val_percent: 0.2
  run_name: ''
  print_every: 5
  # data_augmentation: # TODO: data augement.
  #   horizontal_flip: True
evaluate: # TODO: actually take eval into account.
  batch_size: 50 
verbose: True