# possibly move to Hydra (FB) if things get complex.
dataset:
  data_dir: ../data/farsight
  depth_foldername: depth
  img_foldername: img
model:
  use_cuda: True
  use_saved: True
  path: 12_30_17-09-42_sanity-fold-full-dataset-w-aug
  weight_init: True
  name: UNet
  use_bn: True
  loss: rmsle
  # randomdata?
  # shuffledata?
  lr: 1.e-2
train:
  batch_size: 4
  epochs: 1000
  subset_size:
  use_folds: True
  val_round: True
  shuffle_val: True
  val_percent: 0.2
  run_name: 'sanity-fold-full-dataset-w-aug'
  print_every: 1
  save: True
  save_every: 50
  data_augmentation:
    horizontal_flip: True
    flip_p: 0.5
    color_jitter: True
    gaussian_blur: True
    gaussian_noise: True
    # possibly add std and probability for augs over here?

evaluate: # TODO: actually take eval into account.
  batch_size: 10
  hist: False
verbose: True
random_seed: 42