# possibly move to Hydra (FB) if things get complex.


dataset:
  data_dir: ../data/farsight
  depth_foldername: depth
  img_foldername: img

misc:
  verbose: True
  random_seed: 42 # if none won't have constant seed.
  use_cuda: True

checkpoint:
  # if you load a checkpoint, run_name is ignored.
  # if save_every is empty, it won't save.
  use_saved: True
  saved_path: 01_06_14-37-08_test_save_arch
  run_name: test_save_arch
  save_every: 1

model:
  # is irrelevant if you're loading a saved model.
  # arch is prebuilt into the .pt file. easier to handle it.
  weight_init: True
  name: toynet
  use_bn: True
  use_double_bn: True
  use_dropout: False

optim:
  loss: rmsle
  lr: 1.e-2
  use_lr_scheduler: False
  # randomdata?
  # shuffledata?

train:
  batch_size: 4
  epochs: 1000
  subset_size: 50
  use_folds: True
  print_every: 100

validation:
  batch_size: 10
  val_round: True
  val_percent: 0.2
  shuffle_val: True
  hist: False

data_augmentation:
  flip_p: 0.5
  horizontal_flip: True
  color_jitter: True
  gaussian_blur: True
  gaussian_noise: True
  # possibly add std and probability for augs over here?
